log:
    level: 'trace'
    consoleLogger: false
    fileLogger: true
    filename: 'smart-router.log'
    maxSize: 50000000
    maxFiles: 10
nagios:
    maximumNumberOfEventsToKeep: 100
https:
    use: false
    pfx_path: 'path/to/pfx'
    pfx_passphrase: 'passphrase'

rabbitmqReconnectDelay: 10000
delayBeforeDeletingInactiveQueue: 900000
