log:
    level: 'trace'
    filename: 'smart-router.log'
nagios:
    maximumNumberOfEventsToKeep: 100
https:
    use: false
    pfx_path: 'path/to/pfx'
    pfx_passphrase: 'passphrase'

rabbitmq_reconnect_delay: 10000
